# Generated by Django 3.0.4 on 2020-03-27 16:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('stop_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=20)),
                ('number_of_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Connection')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Vehicle')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='connection',
            name='laststop_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LastStop', to='webapp.Place'),
        ),
        migrations.AddField(
            model_name='connection',
            name='starting_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FirstStop', to='webapp.Place'),
        ),
    ]
