# Generated by Django 3.0.4 on 2020-03-27 17:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Max length: 50', max_length=50)),
                ('last_name', models.CharField(help_text='Max length: 50', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[0-9]$', 'This is not a valid phone number.')])),
                ('pesel', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]$', 'This is not a valid PESEL number.')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance', models.PositiveIntegerField(help_text='Please enter the distance in kilometers.')),
                ('price', models.PositiveIntegerField(help_text='Please enter an integer value.', validators=[django.core.validators.MinValueValidator(1)])),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('stop_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(help_text='Max length: 20', max_length=20)),
                ('number_of_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('model_fullname', models.CharField(blank=True, default='Unknown', help_text='Please enter the full name of the vehicle model.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Connection')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Max length: 50', max_length=50)),
                ('last_name', models.CharField(help_text='Max length: 50', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[0-9]$', 'This is not a valid phone number.')])),
                ('pesel', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]$', 'This is not a valid PESEL number.')])),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Vehicle')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='connection',
            name='laststop_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LastStop', to='webapp.Place'),
        ),
        migrations.AddField(
            model_name='connection',
            name='starting_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FirstStop', to='webapp.Place'),
        ),
    ]
