# Generated by Django 3.0.4 on 2020-04-29 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pesel',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', 'This is not a valid PESEL number.')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[0-9]{9}$', 'This is not a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='pesel',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', 'This is not a valid PESEL number.')]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[0-9]{9}$', 'This is not a valid phone number.')]),
        ),
    ]
